### ISSUE TITLE
Serverless deploy  issues

### ISSUE THREAD

**Issue by ebisbe** [Saeris/Flickr-Wormhole#14]
Hello, 

I got some issues when deploying to AWS. 
```
Endpoint response body before transformations: 
{"errorMessage":"Cannot find module 'graphql-playground/middleware'","errorType":"Error",
"stackTrace":["Function.Module._load (module.js:417:25)",
"Module.require (module.js:497:17)",
"require (internal/module.js:20:19)",
"Object.<anonymous> (/var/task/src/index.js:2:152275)",
"__webpack_require__ (/var/task/src/index.js:1:355)",
"Object.<anonymous> (/var/task/src/index.js:2:152030)",
"__webpack_require__ (/var/task/src/index.js:1:355)",
"Object.<anonymous> (/var/task/src/index.js:2:11756)",
"__webpack_require__ (/var/task/src/index.js:1:355)"]}
```

I just did `sls deploy`. I've seen that installing with yarn is better because npm misses some packages but when deploying using serverless-webpack it uses by default NPM . Any idea how to got it working?

Thanks!

**Comment by Saeris** [comment]
It's been a few weeks since I last made a deploy. Haven't had the time to investigate on this, but my immediate guess would be is that the serveless framework has likely pushed a new version since I last made a commit and I didn't pin the dependency versions, so that may be the source of your problem.

`graphql-playground` is not necessary for the project to work, it's merely an alternative GUI you can use instead of `graphiql`, and I'm sure that has been updated since I added it as well. I can't give you a timeline for when I'll do some updates.

As for serverless using NPM instead of yarn, while I use yarn myself, I don't know enough about how serverless-webpack works in order to configure it to use yarn instead. Best bet there would be to go read through it's docs/source and file an issue there for that specifically.

**Comment by ebisbe** [comment]
It's working now. I tried your code directly and got the same errors so I dig arround. 
- I commentend the graphql-playground as you stated from the file using it.
- Serverless-webpack has a feature to force add packages so I use it to add that packages that were not included with npm.
